trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(51bb037a-4a23-4c3b-afe4-56f5da47bb20)'
    KeyVaultName: 'DemoKVDevops'
    SecretsFilter: '*'
    RunAsPreJob: true
- task: CmdLine@2
  inputs:
    script: 'echo $(Password) > secret.txt'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: 'secret.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'